### ISSUE TITLE
can't run setup

### ISSUE THREAD

**Issue by dizzyd719** [yboetz/pyznap#12] opened 2018-10-06 12:15 UTC
getting the following error:

```
root@SERVER:~# pyznap setup

Traceback (most recent call last):
  File "/usr/local/bin/pyznap", line 7, in <module>
    from pyznap.main import main
  File "/usr/local/lib/python2.7/dist-packages/pyznap/main.py", line 18, in <module>
    from .utils import read_config, create_config
  File "/usr/local/lib/python2.7/dist-packages/pyznap/utils.py", line 312
    host, *_ = ssh.get_transport().getpeername()
          ^
SyntaxError: invalid syntax
root@SERVER:~#
```

**Comment by yboetz** [comment] 2018-10-06 12:59
Hi

You have to install pyznap in your python 3 (>=3.5) environment. If you install it in your system python installation, then do (as your root user)

    pip3 install --user pyznap

If you have a python3 virtualenv set up then activate it and then do

    pip install pyznap

**Comment by dizzyd719** [comment] 2018-10-06 13:46
sorry i'm not much of a python person --

under my root user i did

pip uninstall pyznap

then i switched to my user 

pip install pyznap


and i get the same error

**Comment by yboetz** [comment] 2018-10-06 14:32
Uninstall pyznap again. Then switch to the root user and do

    pip3 install --user pyznap

Note that it says `pip3` not just `pip`. Most linux systems have both python2 and python3 installed by default. `pip` then installs things for python2 and `pip3` installs things for python3. You need to use the python3 one.

**Comment by yboetz** [comment] 2018-10-08 12:34
Did this solve your problem?

**Comment by dizzyd719** [comment] 2018-10-09 15:46
k@SERVER:~$ pip uninstall pyznap
Cannot uninstall requirement pyznap, not installed
k@SERVER:~$ pip3 uninstall pyznap
Cannot uninstall requirement pyznap, not installed
k@SERVER:~$ sudo -i
root@SERVER:~# pip uninstall pyznap
Cannot uninstall requirement pyznap, not installed
root@SERVER:~# pip3 uninstall pyznap
Cannot uninstall requirement pyznap, not installed
root@SERVER:~#
root@SERVER:~# pip3 install --user pyznap
Collecting pyznap
  Using cached
https://files.pythonhosted.org/packages/a1/68/ddfe945dc8a92d9f82035620db7a37fd894c400581120e473f36ea4d498b/pyznap-1.0.2-py3-none-any.whl
Requirement already satisfied: paramiko>=2.4.1 in
./.local/lib/python3.6/site-packages (from pyznap)
Requirement already satisfied: configparser>=3.5.0 in
./.local/lib/python3.6/site-packages (from pyznap)
Requirement already satisfied: pyasn1>=0.1.7 in
./.local/lib/python3.6/site-packages (from paramiko>=2.4.1->pyznap)
Requirement already satisfied: cryptography>=1.5 in
/usr/lib/python3/dist-packages (from paramiko>=2.4.1->pyznap)
Requirement already satisfied: bcrypt>=3.1.3 in
./.local/lib/python3.6/site-packages (from paramiko>=2.4.1->pyznap)
Requirement already satisfied: pynacl>=1.0.1 in
/usr/lib/python3/dist-packages (from paramiko>=2.4.1->pyznap)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3/dist-packages
(from bcrypt>=3.1.3->paramiko>=2.4.1->pyznap)
Requirement already satisfied: cffi>=1.1 in
./.local/lib/python3.6/site-packages (from
bcrypt>=3.1.3->paramiko>=2.4.1->pyznap)
Requirement already satisfied: pycparser in
./.local/lib/python3.6/site-packages (from
cffi>=1.1->bcrypt>=3.1.3->paramiko>=2.4.1->pyznap)
Installing collected packages: pyznap
Successfully installed pyznap-1.0.2

root@SERVER:~# /root/.local/bin/pyznap setup
Oct 09 15:45:13 INFO: Starting pyznap...
Oct 09 15:45:13 INFO: Initial setup...
Oct 09 15:45:13 INFO: Creating directory /etc/pyznap/...
Oct 09 15:45:13 INFO: Creating sample config /etc/pyznap/pyznap.conf...
Oct 09 15:45:13 INFO: Finished successfully...


so looks like it works, but i can't run it under my user. I'll continue
with the installation instructions

**Comment by dizzyd719** [comment] 2018-10-09 16:03
> Did this solve your problem?

also, does this take a snapshot recursively?

I have rpool with more datasets under that


and can I just add another pool by adding a second line to the config?

I have DATA and rpool pools

so i have one section [rpool] and [data]

**Comment by yboetz** [comment] 2018-10-09 16:38
You're supposed to run it as root user, as ZFS needs root permissions to run.

And yes, it takes snapshots recursively, always. For multiple pools you just create two sections `[rpool]` and `[data]`, with the given policy for each dataset.

**Comment by yboetz** [comment] 2018-10-12 14:13
If everything works as intended I will close this issue.

**Closed** 2018-10-12 14:13 UTC
